apiVersion: v1
kind: Service
metadata:
  name: chaos-api-service
  namespace: chaos-sandbox
  labels:
    app: chaos-api
spec:
  type: ClusterIP
  selector:
    app: chaos-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000