apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: chaos-sandbox
  labels:
    app: chaos-postgres
spec:
  type: ClusterIP
  selector:
    app: chaos-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432